Returns false if code is nil
LucasAndrad/brval pull request #19
Opened 2019-02-05 21:20 UTC by ArmandoAssuncao

Para manter a consistência de retorno do `valid?`, que é apenas `boolean`, adicionei uma validação para sempre retornar false se o valor do `code` for `nil`.

2019-02-05 22:25 UTC, LucasAndrad requested changes

2019-02-05 22:25 UTC, LucasAndrad commented on lib/brval/val.rb
> +      return if @code.nil?
Não sei se isso vai dar certo porque nas classes filhas eu chamo:
```ruby
def mask
  code_mask = super
  code_mask.insert(3, '.').insert(7, '.').insert(11, '-')
end
```
O super vai retornar `nil` e ele vai tentar dar o insert no `code_mask` que vai ser `nil`
O no meu terminal deu isso:
```
NoMethodError (undefined method `insert' for nil:NilClass)
```

Teria que ser algo assim:
```ruby
def mask
  raise ArgumentError if @code.nil?
  code_mask = @code.dup
end
```
Mas ai no método `mask` de todas as classes filhas teria que chamar um rescue lá:
```ruby
def mask
  code_mask = super
  code_mask.insert(3, '.').insert(7, '.').insert(11, '-')
rescue ArgumentError
  return false
end
```

Mas com essa volta toda não faz sentido ter o método mask na classe pai `val.rb`
Então no final de tudo é melhor refatorar ele nas classes Cpf e na Cnpj (são as únicas que tem por enquanto).
Na cpf ficaria assim por exemplo:
```ruby
def mask
  return if @code.nil?
  code_mask = @code.dup
  code_mask.insert(3, '.').insert(7, '.').insert(11, '-')
end
```
E no final o método mask seria apagado da classe `Val`

2019-02-05 22:30 UTC, ArmandoAssuncao commented on lib/brval/val.rb
> +      return if @code.nil?
Vou adicionar esses check.

2019-02-06 00:22 UTC, ArmandoAssuncao commented on lib/brval/val.rb
> +      return if @code.nil?
feito.

2019-02-06 00:26 UTC, LucasAndrad commented
Show, ficou muito boa essa abordagem com o masked

2019-02-06 00:26 UTC, merged